repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: check-executables-have-shebangs
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: no-commit-to-branch
    args: [--branch, main]
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.11.2
  hooks:
  # Run the linter.
  - id: ruff
    args: [ --fix  ]
  # Run the formatter.
  - id: ruff-format
- repo: https://github.com/sqlfluff/sqlfluff
  rev: 3.3.1
  hooks:
    - id: sqlfluff-fix
- repo: https://github.com/RobertCraigie/pyright-python
  rev: v1.1.398
  hooks:
    - id: pyright
- repo: https://github.com/PyCQA/bandit
  rev: 1.7.3
  hooks:
    - id: bandit
