[tools]
uv = "0.6.10"
java = "17"
databricks-cli = "0.245.0"
spark = "3.5.5"

[env]
_.file = { path = ".env", redact = true }

[settings]
python.uv_venv_auto = true

[tasks.spark-start]
description = "Start a Spark Connect server"
run = "$(mise where spark)/spark-3.5.5-bin-hadoop3/sbin/start-connect-server.sh --packages org.apache.spark:spark-connect_2.12:3.5.5"
quiet = true

[tasks.spark-stop]
description = "Stop the Spark Connect server"
run = "$(mise where spark)/spark-3.5.5-bin-hadoop3/sbin/stop-connect-server.sh"
quiet = true

[tasks.run-tests]
description = "Run all pytest tests"
run = "uv run pytest"
quiet = true

[tasks.run-tests-connect]
description = "Run all pytest tests using Spark Connect (make sure it is running first)"
run = "uv run pytest --connect"
quiet = true
